fixed version name check in pipeline

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,7 +21,7 @@ jobs:
         id: get_version
 
       - name: check version name
-        run: '[ ! -z "${{ steps.get_version.outputs.version }}" ] && echo "invalid version" && exit 1'
+        run: '[ -z "${{ steps.get_version.outputs.version }}" ] && echo "invalid version" && exit 1'
 
       - name: Add commit hash to artifact
         run: echo $GITHUB_SHA >> oag/commit-hash.txt
@@ -111,7 +111,7 @@ jobs:
       id: get_version
 
     - name: check version name
-      run: '[ ! -z "${{ steps.get_version.outputs.version }}" ] && echo "invalid version" && exit 1'
+      run: '[ -z "${{ steps.get_version.outputs.version }}" ] && echo "invalid version" && exit 1'
 
     - name: Add commit hash to artifact
       run: echo $GITHUB_SHA >> oag/commit-hash.txt
